export const MESSAGES = {
  ACCOUNT_NOT_ACTIVE: 'Account is not active',
  CREATED: 'Resource created successfully',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  LOGGED_OUT: 'Logged out successfully',
  REFRESH_SUCCESS: 'Token refreshed successfully',
  REQUEST_TIMEOUT: 'Request timeout',
  UNAUTHORIZED: 'Unauthorized access',
  FORBIDDEN: 'Access forbidden',
  VALIDATION_ERROR: 'Validation failed',
  VALIDATION_ARRAY_STRING: 'Validation failed (array string is expected)',
  VALIDATION_BOOLEAN_STRING: 'Validation failed (boolean string is expected)',
  VALIDATION_DATE_REQUIRED: 'Date value is required',
  VALIDATION_DATE_STRING: 'Validation failed (valid date string is expected)',
  VALIDATION_EMAIL: 'Please provide a valid email address',
  VALIDATION_FIRST_NAME_STRING: 'First name must be a string',
  VALIDATION_LAST_NAME_STRING: 'Last name must be a string',
  VALIDATION_NUMERIC_STRING: 'Validation failed (numeric string is expected)',
  VALIDATION_PASSWORD_MIN_LENGTH:
    'Password must be at least 12 characters long',
  VALIDATION_PASSWORD_STRING: 'Password must be a string',
  VALIDATION_REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
  VALIDATION_REFRESH_TOKEN_STRING: 'Refresh token must be a string',
  VALIDATION_ROLE: 'Invalid role provided',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  DATA_FOUND: 'Data found',
  HEALTHY: 'Application is healthy',
  NOT_FOUND: 'Data not found',
  READY: 'Application dependencies are ready',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  INVALID_REFRESH_TOKEN_EXPIRY: 'Invalid refresh token expiry',
  INVALID_TOKEN_TYPE: 'Invalid token type',
  INVALID_TOKEN_OR_USER: 'Invalid token or user not found',
  USER_ALREADY_EXISTS: 'User with this email already exists',
  USER_NOT_FOUND: 'User not found',
  USER_ACCESS_FORBIDDEN: 'You cannot access this user',
};
