service: user-service
provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, 'ap-south-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_DB: ${env:POSTGRES_DB}
functions:
  graphql:
    handler: dist/handler.handler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
