apiVersion: batch/v1
kind: Job
metadata:
  name: ecommerce-prisma-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ecommerce/user-service:latest
          command:
            - yarn
            - prisma:deploy
          envFrom:
            - secretRef:
                name: ecommerce-secrets
