export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  SUPPORT_ADMIN = "SUPPORT_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
}

export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum TokenType {
  ACCESS = "ACCESS",
  REFRESH = "REFRESH",
  PASSWORD_RESET = "PASSWORD_RESET",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  OTP = "OTP",
  PASSWORD_SETUP = "PASSWORD_SETUP",
}
