export const MESSAGES = {
  ACCOUNT_INACTIVE: 'Account is not active',
  APP_RUNNING: 'Server is running',
  ARRAY_STRING_EXPECTED: 'Validation failed (array string is expected)',
  BOOLEAN_STRING_EXPECTED: 'Validation failed (boolean string is expected)',
  CREATED: 'Resource created successfully',
  DATE_REQUIRED: 'Date value is required',
  DATE_STRING_EXPECTED: 'Validation failed (valid date string is expected)',
  DATABASE_SEED_FAILED: 'Database seed failed',
  ENVIRONMENT_VALIDATION_FAILED: 'Environment validation failed',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  EMAIL_VALID: 'Please provide a valid email address',
  FIRST_NAME_STRING: 'First name must be a string',
  INVALID_ACCESS_TOKEN: 'Invalid token or user not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  INVALID_REFRESH_TOKEN_EXPIRY: 'Invalid refresh token expiry',
  INVALID_ROLE: 'Invalid role provided',
  INVALID_TOKEN_TYPE: 'Invalid token type',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  NUMERIC_STRING_EXPECTED: 'Validation failed (numeric string is expected)',
  PASSWORD_MIN_LENGTH: 'Password must be at least 12 characters long',
  PASSWORD_STRING: 'Password must be a string',
  REFRESH_SUCCESS: 'Token refreshed successfully',
  REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_STRING: 'Refresh token must be a string',
  REQUEST_TIMEOUT: 'Request timeout',
  SEED_ADMIN_CREATED: 'Seeded admin user',
  SEED_ADMIN_EXISTS: 'Seed skipped. Admin already exists',
  TEST_DATABASE_NAME_REQUIRED:
    'E2E tests must use a database name containing "test"',
  TEST_DATABASE_URL_INVALID: 'TEST_DATABASE_URL must be a valid Postgres URL',
  TEST_DATABASE_URL_REQUIRED:
    'TEST_DATABASE_URL is required when NODE_ENV=test',
  UNAUTHORIZED: 'Unauthorized access',
  USER_ACCESS_FORBIDDEN: 'You cannot access this user',
  USER_EMAIL_EXISTS: 'User with this email already exists',
  USER_NOT_FOUND: 'User not found',
  LAST_NAME_STRING: 'Last name must be a string',
  FORBIDDEN: 'Access forbidden',
  VALIDATION_ERROR: 'Validation failed',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  DATA_FOUND: 'Data found',
  NOT_FOUND: 'Data not found',
};
