syntax = "proto3";

package user;

service UserService {
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  rpc GetUser (GetUserRequest) returns (UserResponse);
  rpc GetUserByEmail (GetUserByEmailRequest) returns (UserResponse);
  rpc ListUsers (ListUsersRequest) returns (ListUsersResponse);
  rpc UpdateUser (UpdateUserRequest) returns (UserResponse);
  rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
}

message CreateUserRequest {
  string email = 1;
  string passwordHash = 2;
  optional string firstName = 3;
  optional string lastName = 4;
  optional string role = 5;
}

message GetUserRequest {
  string id = 1;
}

message GetUserByEmailRequest {
  string email = 1;
}

message ListUsersRequest {
  int32 page = 1;
  int32 limit = 2;
}

message UpdateUserRequest {
  string id = 1;
  optional string firstName = 2;
  optional string lastName = 3;
  optional string role = 4;
}

message DeleteUserRequest {
  string id = 1;
}

message DeleteUserResponse {
  bool deleted = 1;
}

message UserResponse {
  string id = 1;
  string email = 2;
  string passwordHash = 3;
  optional string firstName = 4;
  optional string lastName = 5;
  string role = 6;
  string status = 7;
  string createdAt = 8;
  string updatedAt = 9;
}

message ListUsersResponse {
  repeated UserResponse data = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 total = 4;
}
